# docker-compose.yml
version: '3.8'
services:
  myapp:
    image: "myapp:v1"
    restart: unless-stopped
    volumes:
      - ./volumes/data:/app/data
      - ./volumes/resources:/app/html/resources
    ports:
      - 3000:3000
# networks:
#   default:
#     external:
#       name: main